### ISSUE TITLE
onChange Handler

### ISSUE THREAD

**Issue by zOthix** [gtgalone/react-quilljs#1]
Hi, i found your hook really useful and good, can you please tell me how do i add my onchange handler in it?

**Comment by gtgalone** [comment]
> Hi, i found your hook really useful and good, can you please tell me how do i add my onchange handler in it?

@zOthix Thank you for using.

In the return parameters, There is editor object.

So, You can use editor object like quill to add on change handler - https://quilljs.com/docs/api/#on

In your case,

```jsx
useEffect(() => {
  editor.on('text-change', () => {
    console.log('editor was changed!');
  };

  // This is in quill document above link. Replace just quill to editor.
  //
  // quill.on('text-change', function() {
  //  console.log('Text change!');
  // });
}, [editor]);
```

I will consider changing object name from editor to quill.  Thank you :)

**Comment by zOthix** [comment]
thankyou, can u please check this
https://dpaste.org/eCND
i want to be able to add these basic props in it, how can i do that.

**Comment by gtgalone** [comment]
@zOthix 
It could be like this.
Just refer this. and You can figure out based on this code. :)
```jsx
// ReactQuill Component
export default ({ onChange, value, placeholder, className }) => {
  const { quill, quillRef } = useQuill({ placeholder });

  useEffect(() => {
    quill.on('text-change', onChange);
    quill.clipboard.dangerouslyPasteHTML(value);
  }, [quill, value, onChange]);

  return (
    <div style={{ width: 500, height: 300 }} className={className}>
      <div ref={quillRef} />
    </div>
  );
};
```
