### ISSUE TITLE
안녕하세요. 라이브러리의 사용법에 대해 질문드립니다.

### ISSUE THREAD

**Issue by jonsoku2** [gtgalone/react-quilljs#10]
먼저 좋은 라이브러리를 개발해주셔서 감사합니다.

질문이있어서 이슈에 남깁니다. 

기존 react-quill을 쓸때에는 onChange와 value를 이용해서 에디터 안에서 작성되어지는 걸 컨트롤할 수 있는데, 

이 라이브러리에서는 어떻게 컨트롤할 수 있을까요??

**Comment by gtgalone** [comment]
@jonsoku2 안녕하세요!

라이브러리를 이용해주셔서 감사합니다.

https://github.com/gtgalone/react-quilljs/issues/1 

상단의 클로징된 이슈를 보시면 답변이 될 것 같아요.

감사합니다.
