### ISSUE TITLE
Quill cursors are not showing correctly

### ISSUE THREAD

**Issue by grizafisjr** [gtgalone/react-quilljs#11]
I was trying to integrate the `quill-cursors` with `react-quilljs`, but I am having some issue for showing that.

This is the live example: https://codesandbox.io/s/react-quilljsbasic-forked-8rhl3?file=/src/App.js:1390-1641

![image](https://user-images.githubusercontent.com/52982818/104963031-f77ef500-59d9-11eb-8843-8d9f04d99de6.png)

**Comment by trustyonlinemart** [comment]
@grizafisjr 
Thank you for using.

I will check after working.

**Comment by gtgalone** [comment]
@grizafisjr 
Thank you for using. 

Now I am working. After this, I will check it.

**Comment by gtgalone** [comment]
@grizafisjr 
Could you try more?

I think this is working and no problem with react-quilljs.

This library is just mapping Quill. There is no under the hood.

**Comment by grizafisjr** [comment]
@gtgalone I tried again and I am still seeing same issue.
Did you play around with the codesandbox I provided in the description?

**Comment by gtgalone** [comment]
@grizafisjr 

I would like to. But for now, I am so busy building services. I will try when I have time.
