### ISSUE TITLE
Unable to install react-quilljs on React 17

### ISSUE THREAD

**Issue by masumluf** [gtgalone/react-quilljs#14]
Hello I am unable to installing react-quilljs on my project where react verstion is "^17.0.1". Any Solution for that ?

**Comment by gtgalone** [comment]
@masumluf 

Hello.

https://codesandbox.io/s/react-quilljsbasic-forked-j0pli

Can you check this code sandbox?

with react 17.0.1 works fine.

**Comment by masumluf** [comment]
Sorry I can not install it using npm , here is my error code 
` npm i react-quilljs
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: fusion@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.12.0" from react-quilljs@1.2.12
npm ERR! node_modules/react-quilljs
npm ERR!   react-quilljs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/****/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/****/.npm/_logs/2021-02-19T08_27_59_386Z-debug.log`

**Comment by gtgalone** [comment]
@masumluf 

Okay you can try remove

`rm -rf node_modules`

`rm -rf package-lock.json`

and then

`npm install`

**Comment by masumluf** [comment]
still same issue , 
`➜  fusion git:(main) ✗ npm i react-quilljs
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: fusion@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.12.0" from react-quilljs@1.2.12
npm ERR! node_modules/react-quilljs
npm ERR!   react-quilljs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by gtgalone** [comment]
@masumluf 

Oh you don't have 16.12 react

you can try

`npm install --legacy-peer-deps`

after that let me know :)

**Comment by masumluf** [comment]
same issue 
`npm i react-quilljs
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: fusion@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.12.0" from react-quilljs@1.2.12
npm ERR! node_modules/react-quilljs
npm ERR!   react-quilljs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by gtgalone** [comment]
@masumluf

Okay thank you for your passion.

I have just published react-quiiljs 1.2.13 version with react 17.0.1.

you can upgrade it :)

**Comment by masumluf** [comment]
Done , Thank you.

**Comment by masumluf** [comment]
One more question what is the difference between react-quill and react-quillJs ? I am using it in my nextJs project how can I import css in a particular component ?

**Comment by gtgalone** [comment]
@masumluf 

One more question what is the difference between react-quill and react-quillJs ?
**react-quilljs is for react hooks, I think react-quill is for class base.**

I am using it in my nextJs project how can I import css in a particular component ?
you can check https://nextjs.org/docs/basic-features/built-in-css-support

**Comment by ibadeeCodes** [comment]
I am using react version  17.0.1.
React quill is not getting installed still.

**Comment by gtgalone** [comment]
@ibadeeCodes Thank you for using.

I have tested with react 17.0.2 and it is working well.

can you share package.json?

**Comment by sargtier1** [comment]
Hey y'all, I'm running into the same issues, just trying to setup a basic next.js app to test out quill to see if it's what I'm looking for in my main project. So what's really the issue here? `Package.json` looks like this:

```
{
  "name": "richtext-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "eslint": "8.10.0",
    "eslint-config-next": "12.1.0"
  }
}

```

**Comment by gtgalone** [comment]
@sargtier1 Thank you for using.

I just tried to installing package with your package.json.

`yarn add react-quilljs quill` is work for me.

Are you using NPM?

**Comment by sargtier1** [comment]
Het @gtgalone,
I'm trying to use `react-quill` specifically, not `react-quilljs`. I am using NPM

**Comment by gtgalone** [comment]
@sargtier1 Oh here is react-quilljs.

You should add issue on https://github.com/zenoamaro/react-quill

**Comment by sargtier1** [comment]
Ahh im an idiot, didn't realize i was on the wrong github. Thank you

**Comment by sargtier1** [comment]
Also it looks like i fixed it by appended `--legacy-peer-deps` to the end of my install command. This should help anyone with the issue in this thread!

**Comment by vimalp-itpath** [comment]
can't install form react version 18
shows error like 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-quill@1.2.13.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
