### ISSUE TITLE
React-quilljs is not loading when Tab change on Material UI

### ISSUE THREAD

**Issue by masumluf** [gtgalone/react-quilljs#15]
Hello I have been working on react quilljs I have 3 tabs, if i navigate another tab and back to the quill editor tab it goes to disappear. here is my codesandbox
https://codesandbox.io/s/lucid-gareth-v5zfo

**Comment by gtgalone** [comment]
@masumluf 

Okay. Friend

Make new component for quill.

https://codesandbox.io/s/eager-mclaren-b3lm7?file=/src/App.js
