### ISSUE TITLE
Image link is not attaching in the body .

### ISSUE THREAD

**Issue by masumluf** [gtgalone/react-quilljs#16]
Hello,

I am trying to upload post using react-quilljs, I have implemented everything as per as your document and everything is working fine but whe I upload any image the image url is coming from server and image also is showing in the editor as like as uploaded photo in codesandbox named editor.js, but when I submit post link is disappear from body content. I have shared my codesandbox link below and screenshot in the attachment

https://codesandbox.io/s/hungry-forest-o013r

**Comment by gtgalone** [comment]
@masumluf 

Hello, That link is not working and You should figure it out.

I think that is not a problem of this package.
