### ISSUE TITLE
using react-quilljs v 1.2.13 but nothing in div

### ISSUE THREAD

**Issue by jerome-diver** [gtgalone/react-quilljs#17]
your example first code for 
```javascript
<div ref={quillRef}/>
```
Inside a Form, then inside an InputGroup (from react-bootstrap library)...
But this div doesn't contain anything inside.
I well imported useQuill hook and build const from this, but nothing inside the div ref call.

I'm using React.js v 17.0.1 in SSR mode and link with quill stylesheet on server side with my template (pug, but anyway, the link is there...)

what should i do to fix the problem (i don't know where the problem is coming from) ? I suppose that react-quilljs do the job to create quill Javascript object from his hook... do i have to do something more you didn't indicate in your Readme.md page ?

**Comment by gtgalone** [comment]
@jerome-diver 

Hello!

You can only use quill client side and SSR is not working on quill library.

my react-quilljs check if ssr or not and then to avoid ssr.

even through you use react-bootstrap. you can use div tag without InputGroup or Form.

just use <div ref={quillRef} /> inside InputGroup like below

```
<InputGroup>
  <div ref={quillRef} />
</InputGroup>
```
