### ISSUE TITLE
Not compatible with react 16.8.6

### ISSUE THREAD

**Issue by mehdifracso** [gtgalone/react-quilljs#18]
Hi,

We are using react 16.8.6 internaly at our company so I am obliged to work with it (tried to upgrade to react 17 but it breaks other dependencies) so I have to deal with this version.

My problem is when I try install react-quilljs, I have the following error log:
`npm install react-quilljs quill
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-whiteapp@0.0.1
npm ERR! Found: react@16.8.6
npm ERR! node_modules/react
npm ERR!   react@"16.8.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from react-quilljs@1.2.13
npm ERR! node_modules/react-quilljs
npm ERR!   react-quilljs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

How can I resolve this please?

**Comment by gtgalone** [comment]
@mehdifracso Thank you for using!

You can try with 1.2.11 version without `^`.

`"react-quilljs": "1.2.11"`

**Comment by gtgalone** [comment]
@mehdifracso Thank you for using!

Please use 1.2.14 version.

I have just changed react peer to both 16 and 17 version.
