### ISSUE TITLE
How to use formatLine or insertText?

### ISSUE THREAD

**Issue by 10000multiplier** [gtgalone/react-quilljs#19]
When using certain methods from the API such as:

`quill.insertText(0, 'Hello', 'bold', true);
`

I am getting the following error:

'TypeError: Cannot read property 'insertText' of undefined'.

Any tips?

Awesome library by the way, thank you.

**Comment by gtgalone** [comment]
@10000multiplier Thank you for using!

At first rendering, quill is undefined.

And second rendering, quill has Quill object.

So you have to check if quill is undefined or not.

like below example,

https://github.com/gtgalone/react-quilljs#with-initial-value

**Comment by 10000multiplier** [comment]
Yay it's working 😄
