### ISSUE TITLE
Registering plugins

### ISSUE THREAD

**Issue by benswinburne** [gtgalone/react-quilljs#2]
How might I go about registering plugins using `Quill.register()` for example?

I'm looking at adding https://github.com/contentco/quill-emoji/ but registering the toolbars and modules happens before I can get the quill object and register additional plugins/formats etc.

**Comment by gtgalone** [comment]
@benswinburne Thank you for using.

In your case, You have to use custom options.

According to https://github.com/contentco/quill-emoji/#usage 

```jsx
import 'quill-emoji'; // Important import emoji plugin

const toolbarOptions = {
  container: [
    ['bold', 'italic', 'underline', 'strike'],
    ['emoji'],   
  ],
  handlers: {'emoji': function() {}}
}
const formats = ['bold', 'italic', 'underline', 'strike', 'emoji']; // Important Sync with container array above.
const modules = {
  // ...
  toolbar: toolbarOptions,
  "emoji-toolbar": true,
  "emoji-textarea": true,
  "emoji-shortname": true,
}

const { quill, quillRef } = useQuill({ modules, formats });

React.useEffect(() => {
  // Just example for you. You don't have to add this line below. (optional)
  if (quill) { quill.register({ 'formats/emoji': EmojiBlot }, true); } 
}, [quill])
```

I just have finished with emoji screenshot below.

<img width="500" alt="Screen Shot 2020-02-18 at 11 49 12 PM" src="https://user-images.githubusercontent.com/23162037/74802942-4d6a8a80-52a9-11ea-8b5b-24c969b893d9.png">

Figure out about css style emoji popover :)

**Comment by benswinburne** [comment]
Hi @gtgalone thanks for getting back so quickly. Whilst the example above worked I'm not sure how to apply that information to other plugins. For example, most plugins suggest calling register before instantiating Quill with options.

Without doing that and using an effect to register using the returned Quill I always seem to get errors about unregistered plugins (because i'm instantiating the plugins before registering i guess).

For example, combining your reply above with an additional plugin ([Wordcounter](https://www.npmjs.com/package/quill-wordcounter))

```
import { useQuill } from 'react-quilljs';
import 'quill-emoji';
import Wordcounter from 'quill-wordcounter';
import 'quill/dist/quill.snow.css';
import 'quill-emoji/dist/quill-emoji.css';

  const toolbarOptions = {
    container: [['bold', 'italic', 'strike'], ['emoji']],
  };

  // Important Sync with container array above.
  const formats = ['bold', 'italic', 'strike', 'emoji'];
  const modules = {
    counter: {
      container: '#counter',
      unit: 'word',
    },
    'emoji-toolbar': true,
    'emoji-textarea': false,
    'emoji-shortname': true,
    toolbar: toolbarOptions,
  };

  const { quill, quillRef } = useQuill({ formats, modules });

  useEffect(() => {
    quill && quill.register('modules/wordcounter', Wordcounter);
  }, [quill]);
```

> quill Cannot import modules/counter. Are you sure it was registered? 
> quill Cannot load counter module. Are you sure you registered it?

Does it make sense that i should be able to pass in a register object/array to useQuill so i can register modules/formats etc before passing in the configurations for them with `modules`, `formats` etc or am I missing the point?

Thanks again for your help.

**Comment by gtgalone** [comment]
@benswinburne 

Huge Thank you for this.

I just add Quill class in return values.

Please update react-quilljs version to 1.2.0

I just have released new package version with Example code.

Example code
https://github.com/gtgalone/react-quilljs#with-adding-plugins

**Comment by benswinburne** [comment]
Perfect, that'll work fine! Thanks!
