### ISSUE TITLE
Quill Magic URL can't unlink a link with a URL format

### ISSUE THREAD

**Issue by FitTech961** [gtgalone/react-quilljs#20]
In the readme it's mentioned to use `quill-magic-url` for auto link while typing and on paste. But there's a bug when you try to unlink a link with a url format it will automatically bi relinked.

https://user-images.githubusercontent.com/74727995/112153711-3a349780-8bec-11eb-8503-560260d6f8ab.mov

The functionality of removing a link is not in the `quill-magic-url` any idea where I can find it?

**Comment by gtgalone** [comment]
@FitTech961 Thank you for using.

I think that occurs only with same line.

And you should make an issue on `quill-magic-url` repository.
