### ISSUE TITLE
quill-better-table support?

### ISSUE THREAD

**Issue by devhyunjae** [gtgalone/react-quilljs#21]
Hi,
thanks for the awesome lib.

Is this lib possible to integrate with https://github.com/soccerloway/quill-better-table ?
or a new table feature?

If yes, can you provide a doc or example csb?

**Comment by gtgalone** [comment]
@devhyunjae Thank you for using.

Sure. There are some examples for adding plugins.

https://github.com/gtgalone/react-quilljs#with-adding-plugins

**Comment by devhyunjae** [comment]
@gtgalone I tried, but not working. Can you take a look for a sec?

https://codesandbox.io/s/react-quilljsbasic-forked-1k7b0?file=/src/App.js

**Comment by gtgalone** [comment]
You should check this issue.

https://github.com/soccerloway/quill-better-table/issues/42

It belongs to `quill-better-table` plugin

**Comment by devhyunjae** [comment]
Yeah i have also seen that :(
Thanks for your precious time!

**Comment by AlexanderDLe** [comment]
> Yeah i have also seen that :(
> Thanks for your precious time!

Did you ever get it working? Or did you ever find an alternative way to build an editor with tables?

**Comment by 007jiang7442262** [comment]
I also encountered such a problem. Is there a way to solve it now?

**Comment by gtgalone** [comment]
@007jiang7442262 I think he stops to contribute that plugin you should look for other way.

**Comment by wardaNaqvi** [comment]
is quill-better-table supports on react?
