### ISSUE TITLE
How do I refresh my quill

### ISSUE THREAD

**Issue by splintor** [gtgalone/react-quilljs#22]
I have an editor which allows "view source". When the user edits the source, the Quill editor is not rendered, but the `quill` editor remembers its state, so when the user is back to the editor, it doesn't turn the `<div>` to a `quill` editor.

How can I reset my `quill` and `quillRef` to apply to the newly rendered `<div>`?

**Comment by gtgalone** [comment]
@splintor Thank you for using.

You may find the way here.(https://quilljs.com/docs/api/)

**Comment by splintor** [comment]
This is not related to the core `quilljs`. It is related to the wrapping hook. I'm looking for a way to reset its state.
Since I couldn't find such a way, I reverted to a workaround - I keep rendering the Quill editor all the time, and just hide it with CSS when the "view source" UI is visible.

**Comment by gtgalone** [comment]
Oh okay.

I thought you need to setState for quill obj for refresh?

If possible, Could you make a pull request?

because you can test in your situation.

We can make it better.

**Comment by splintor** [comment]
My workaround seems good enough, so I don't think I'll get to do a pull request.

**Comment by gtgalone** [comment]
That sounds good :)
