### ISSUE TITLE
Using together with quill-image-compress.

### ISSUE THREAD

**Issue by danielcai1987** [gtgalone/react-quilljs#24]
Hi Jehun, peace to you brother.

I found your react-quilljs is very useful.
I'm new to it, could you guide me on how to use the [quill-image-compress](https://www.npmjs.com/package/quill-image-compress) library together?

I tried to add the quill-image-compress and register it.
![image](https://user-images.githubusercontent.com/5369599/122026201-9890a100-cdfc-11eb-8765-2cab27799d3d.png)

But I got an error in the console.
![image](https://user-images.githubusercontent.com/5369599/122026498-d8578880-cdfc-11eb-9155-8d4651bfeb66.png)

Thank you. God bless.
Daniel

**Comment by gtgalone** [comment]
@danielcai1987 Thank you for using!

I have checked with this plugin on code sandbox.

It is working well.

Please check it.

https://codesandbox.io/s/react-quilljsbasic-forked-lw2ku?file=/src/App.js

**Comment by danielcai1987** [comment]
That's very helpful! thank you brother!
