### ISSUE TITLE
Dynamically switch between the snow theme and the bubble theme

### ISSUE THREAD

**Issue by noobnoobdc137** [gtgalone/react-quilljs#26]
How to dynamically switch between the snow theme and the bubble theme

I want to give the users the to choose which editor they want to use

How do I do that the source code is ``useRef`` which will not trigger a re render

And Thank you for your effort

**Comment by gtgalone** [comment]
@noobnoobdc137 Thank you for using.

You can do with import css both and changing state for quill module.
