### ISSUE TITLE
Can't make this work in a reactjs-popup form

### ISSUE THREAD

**Issue by BryanDollery** [gtgalone/react-quilljs#27]
I've written this up on StackOverflow too:

https://stackoverflow.com/questions/68431935/react-quilljs-and-reactjs-popup-dont-work-together

I'm using `react-quilljs` and `reactjs-popup` together and can't get the quill-based editor to show in my modal dialog. I can use the editor on the main page with no issues but it will not work on the popup.

I have the expected imports:
```js
import React from "react";
import Popup from "reactjs-popup";
import "reactjs-popup/dist/index.css";
import { useQuill } from "react-quilljs";
```
And my component looks something like this:
```js
const NewIdeaDialog = ({ showNewIdea }) => {
  const { quill, quillRef } = useQuill();
  return (
    <Popup open={showNewIdea} nested>
      <div>
        <form action="" method="">
          <label for="IdeaDetails">Details</label>
          <div style={{ width: 500, height: 300 }} id="IdeaDetails">
            <div ref={quillRef} />
          </div>
        </form>
      </div>
    </Popup>
  );
}
```
When I set `showNewIdea` to true in the parent component the popup is displayed, as expected, but the quill editor is completely missing. It renders the `#IdeaDetails` div and a child that is `<div></div>` and that's all. The child div is completely empty and devoid of styling.

Am I missing something that will make this work? I can't find any similar issues listed on the web for this problem.

**Comment by gtgalone** [comment]
@BryanDollery Thank you for using!

Please check it out.

https://codesandbox.io/s/react-quilljsbasic-forked-4elv4?file=/src/App.js

**Comment by BryanDollery** [comment]
> @BryanDollery Thank you for using!
> 
> Please check it out.
> 
> https://codesandbox.io/s/react-quilljsbasic-forked-4elv4?file=/src/App.js

Hi @gtgalone, thanks for this it helped solve the problem, though I still don't know the cause.

The difference between your code and mine is that you have wrapped the component containing quill in a popup, whereas I had the popup code in the component. Apparently this makes all the difference. I've also tried my code with `open={true}` and quill also appears then.

I think that maybe quill or your component doesn't like being hidden (`display:none`) and can't deal with the change in that property. 

B
