### ISSUE TITLE
NPM package depends on tslib

### ISSUE THREAD

**Issue by maccuaa** [gtgalone/react-quilljs#3]
v1.2.0 introduced a dependency on tslib in the generated NPM package. When trying to us react-quilljs the following error is thrown:

```
DependencyNotFoundError
Could not find dependency: 'tslib' relative to '/node_modules/react-quilljs/lib/index.js'
```

See [Code Sandbox](https://codesandbox.io/s/react-quilljs-3-ei75s) that reproduces the issue.

You can also see it in this NPM Package diff from [v1.1.3...1.2.5](https://diff.intrinsic.com/react-quilljs/1.1.3/1.2.5#file-esm__index.js)

**Comment by gtgalone** [comment]
@maccuaa 

Really Thank you for the issue!

I have removed tslib v1.2.6.

**Comment by maccuaa** [comment]
v1.2.6 fixes the code sandbox repo. Thanks for the quick fix!
