### ISSUE TITLE
How do you get user input HTML onChange event?

### ISSUE THREAD

**Issue by kaloraat** [gtgalone/react-quilljs#30]
The docs says this:
```
  React.useEffect(() => {
    if (quill) {
      quill.on('text-change', () => {
        console.log('Text change!');
      });
    }
  }, [quill]);
```
But I am interested in getting user input like `event.target.value` or just `event` (in react-quill) to get HTML , just like any WYSIWYG editor do.
`console.log('Text change!');` is not really helpful since no one wants to console log hard coded text, we want user input in HTML format right?

Could you please show me how that's done :)

**Comment by kaloraat** [comment]
I saw I could use `quill.getText()` but that gives me plain text not HTML.

**Comment by gtgalone** [comment]
@kaloraat Thank you for using.

There is many properties in quill and Quill.

You can check it with `console.log`. You will find it.

**Comment by adarsh45** [comment]
> @kaloraat Thank you for using.
> 
> There are many properties in quill and Quill.
> 
> You can check it with `console.log`. You will find it.

Can you specify exactly what to use ?
we can use quillRef.innerHtml but it gives unncessary Html of quill editor itself !
Because it will be completely useless if we can't get user input html formatted text !
Please look into this issue!

**Comment by gtgalone** [comment]
@adarsh45 Sure.

I have just updated readme for this.

https://github.com/gtgalone/react-quilljs#with-onchange-handler
