### ISSUE TITLE
Quill Editor does not work if conditionally rendered

### ISSUE THREAD

**Issue by AmanMinhas** [gtgalone/react-quilljs#31]
If the editor is rendered conditionally it does not work. 

[Codepen](https://codesandbox.io/s/react-quilljsbasic-forked-lnt9g?file=/src/App.js) to reproduce the issue.

**Comment by gtgalone** [comment]
@AmanMinhas Thank you for using!

Element must exists on DOM before quill is initialized.

You should check it #27
