### ISSUE TITLE
How to import quill parchment

### ISSUE THREAD

**Issue by nathanmaru** [gtgalone/react-quilljs#34]
I plan to create a custom format and it says that I have to do it with parchment. But how can I do it using this?

what I want to do:
`var Parchment = Quill.import('parchment');`

what I tried to do:
`useEffect(() => {
		if (quill) {
			console.log(quill.import('parchment'));
		}
	}, [quill]);`

but it says `TypeError: quill.import is not a function`

please help me.

**Comment by SilvaQ** [comment]
just normal import from module, do not try to install or other.
for example:


![image](https://user-images.githubusercontent.com/46706370/132079907-6289da50-1095-47a1-ba7a-95865011a78a.png)
