### ISSUE TITLE
Consider updating useEffect dependencies

### ISSUE THREAD

**Issue by paulm17** [gtgalone/react-quilljs#38]
I kept on getting an intermittent quill instance. 

See video:  https://www.youtube.com/watch?v=kOIolVvyfHE

I changed the useEffect dependencies:

https://github.com/gtgalone/react-quilljs/blob/master/index.ts#L83

From:

```
}, [obj.Quill]);
```

To:

```
}, [obj, isLoaded, options])
```

Now it's consistent, see video:  https://www.youtube.com/watch?v=IgBJhUTD2CI

**Comment by gtgalone** [comment]
@paulm17 Yes. That looks good.

I will have to check about it.

If possible, Feel free to contribute :)

**Comment by paulm17** [comment]
Please check it.  No rush, whenever you get to it and then I will make a PR.  Thanks!

**Comment by gtgalone** [comment]
@paulm17 I have checked about that.

I think I need to check the full code.

So can you make the PR? 

We can figure it for next release.

**Comment by paulm17** [comment]
This is the full code:

```
useEffect(() => {
    if (!obj.Quill) {
      obj.Quill = require("quill") as Quill
    }
    if (obj.Quill && !obj.quill && quillRef && quillRef.current && isLoaded) {
      const opts = assign(options, {
        modules: assign(modules, options.modules),
        formats: options.formats || formats,
        theme: options.theme || theme,
      })
      const quill = new obj.Quill(quillRef.current, opts)

      setObj(assign(assign({}, obj), { quill, editor: quill }))
    }
    setIsLoaded(true)
  }, [obj, isLoaded, options])
```

I'll leave this open.  But I am now moving to tiptap because I have a few issues with Quill that I could not solve.  Thank you for a great library.

**Comment by gtgalone** [comment]
Sure I will close this and then we can solve it continually
