### ISSUE TITLE
Plugin Overwriting modules warning

### ISSUE THREAD

**Issue by HPieters** [gtgalone/react-quilljs#39]
When following the example provided for plugins in the readme (https://github.com/gtgalone/react-quilljs#with-adding-plugins) for the [quil-cursors plugin](https://github.com/reedsy/quill-cursors) I get a warning in my console in my use case. I have a list of notes  and the warning is triggered when a user switches between notes. This might be due to my implementation, I am not exactly sure.

`quill Overwriting modules/cursors with ƒ t(t, e) {`

I found however that if I just globally register the plugin I don't get this warning. Is there anything against doing it this way for a global plugin? 

```javascript
import Quill from "quill";
import { useQuill } from "react-quilljs"
import QuillCursors from "quill-cursors";

Quill.register("modules/cursors", QuillCursors);

export default () => {
  const {quillRef } = useQuill({ modules: { cursors: true } });

  return (
    <div style={{ width: 500, height: 300 }}>
      <div ref={quillRef} />
    </div>
  );
};
```

**Comment by gtgalone** [comment]
@HPieters Thank you for using!

You should refer this

https://github.com/gtgalone/react-quilljs#with-adding-plugins
