### ISSUE TITLE
Placeholder option isn't working

### ISSUE THREAD

**Issue by tim-soft** [gtgalone/react-quilljs#4]
It looks like the placeholder option isn't getting passed to the quill constructor

https://github.com/gtgalone/react-quilljs/blob/master/index.ts#L68

**Comment by gtgalone** [comment]
@tim-soft Thank you so much for reporting a issue.

The Issue was fixed with 1.2.8 :)

**Comment by tim-soft** [comment]
@gtgalone woohoo! Thanks for the quick response

**Comment by romseguy** [comment]
when placeholder prop value changes the editor is not refreshed with new placeholder value

**Comment by gtgalone** [comment]
@romseguy You should re-render editor when placeholder is updated.
