### ISSUE TITLE
How to insert embed image lazy load

### ISSUE THREAD

**Issue by nizarfadlan** [gtgalone/react-quilljs#40]
i want to create an embed lazy load on image tag in react-quilljs but i can't

**Comment by gtgalone** [comment]
@nizarfadlan Thank you for using.

Is there any quill plugins for that?

**Comment by nizarfadlan** [comment]
> Is there any quill plugins for that?

yes need

**Comment by gtgalone** [comment]
What plugin are you trying to?

**Comment by nizarfadlan** [comment]
oh sorry I mean, how to add lazy load attribute to input image in quill

**Comment by gtgalone** [comment]
@nizarfadlan Oh okay,

You should save with delta structure instead of saving string html.

After this you can  handle rich text line by line.

So if you find image you can add <Lazy loading component> or just print it with <p>.

There is a lot of Lazy loading libs in NPM :)
