### ISSUE TITLE
AddRange(): The given range isn't in document. when using onChange value

### ISSUE THREAD

**Issue by nathanmaru** [gtgalone/react-quilljs#44]
Hi! I wonder how can I implement an on text-change and get its html value. I got an error when I use a useState to set my data whenever the text changes. 

it seems that it triggers a re render and just go back to my intial value. Can you guide me on this? The guide on the readme works but if I  update my state variable it gives me this error.

![image](https://user-images.githubusercontent.com/55788297/156662670-90315069-0d4f-4992-97f1-ae86fed3f940.png)

**Comment by gtgalone** [comment]
@nathanmaru Thank you for using!

Please check it out 

https://github.com/gtgalone/react-quilljs#with-initial-value

**Comment by nathanmaru** [comment]
Hello, @gtgalone I use what was indicated in the readme. For some reason when I combine the setting of initiating a default value and on text change, it triggers a re-render because my state changes, and therefore the editor goes back to my initial value. My question is how can I get the value not just by console logging it? can you provide an example using the two?

**Comment by gtgalone** [comment]
Oh okay, If possible, can you share your code with Code Sandbox?

I can help you more.

**Comment by nathanmaru** [comment]
Now that you mention it I re created my component on Code Sandbox and for some reason it works in there so I guess the problem is my code I think I need to take care of this myself thank you for your response.
