### ISSUE TITLE
Missing dependency in useEffect array dependecy

### ISSUE THREAD

**Issue by emasovic5** [gtgalone/react-quilljs#45]
After upgrading to react 18, my editor won't initialize anymore. When I checked your hook I saw that there are some dependencies missing in the dependency array.

[obj.Quill, options, obj, isLoaded]

**Comment by gtgalone** [comment]
@emasovic5 Thank you for using!

I have tested with react 18.0.0.

But it is working well.

https://codesandbox.io/s/react-quilljs-basic-forked-wyc8ps?file=/package.json

Could you post error message?

**Comment by emasovic5** [comment]
There is no error message, the quill instance becomes undefined.

**Comment by gtgalone** [comment]
I think you should try on CodeSandBox with your code.

I have tested with several ways. It is working good.

I will close it. If there is issue on this package, we can reopen it.
