### ISSUE TITLE
Issue with React 17!

### ISSUE THREAD

**Issue by itsmdsameerkhan** [gtgalone/react-quilljs#48]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/46621885/175233057-2f9d30c8-ffe5-41a5-bba9-639383b6d4e9.png">

**Comment by gtgalone** [comment]
@itsmdsameerkhan Thank you for using!

you should install quill too not only react-quilljs.

with 

$ yarn add react-quilljs quill
or
$ npm install react-quilljs quill

**Comment by itsmdsameerkhan** [comment]
got it working, thanks! 🎉
