### ISSUE TITLE
Controlled texteditor

### ISSUE THREAD

**Issue by Abdqadr1** [gtgalone/react-quilljs#49]
Whenever I try to control the editor with useState using the dangerouslyPasteHTML method. The cursor keeps jumping at the front of the text.

**Comment by gtgalone** [comment]
Hello! @Abdqadr1

I guess that looks rendering problem.

Could you test your code and share for me in CodeSandBox https://codesandbox.io/s/react-quilljsbasic-wm0uk?

**Comment by Abdqadr1** [comment]
Check https://codesandbox.io/s/react-quilljsbasic-wm0uk

**Comment by Abdqadr1** [comment]
check https://codesandbox.io/s/react-quilljs-basic-forked-juouk8

**Comment by gtgalone** [comment]
@Abdqadr1 Thanks!

you should add this line 

`quill.setSelection(text.length, text.length);`

```
useEffect(() => {
    if (quill) {
      quill.clipboard.dangerouslyPasteHTML(text);
      quill.on("text-change", (delta, oldDelta, source) => {
        setText(quill.root.innerHTML);
      });
      quill.setSelection(text.length, text.length);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [quill, text]);
  ```

**Comment by Abdqadr1** [comment]
Okay. Thank you
