### ISSUE TITLE
Weird behaviour on inplementation

### ISSUE THREAD

**Issue by jsnavarroc** [gtgalone/react-quilljs#50]
It has to do with the fact that it takes time to load the quill, when rendering the quill parameters they arrive empty.

![image](https://user-images.githubusercontent.com/28201235/179319853-ec215026-d3f7-41ca-aa8b-c38a40a3288b.png)

**Comment by gtgalone** [comment]
Hello @jsnavarroc !

Could you provide your code? 

[Code Sandbox Playground Example](https://codesandbox.io/s/react-quilljsbasic-wm0uk)

**Comment by jsnavarroc** [comment]
Already fixed in this pull request 
https://github.com/gtgalone/react-quilljs/pull/51/files

**Comment by gtgalone** [comment]
@jsnavarroc Awesome!

Thanks for helping me!

I just published with your fixes to v1.3.1.

Please update it!
