### ISSUE TITLE
blur event not working 

### ISSUE THREAD

**Issue by fvn-manhtd** [gtgalone/react-quilljs#52]
I want to set blur on editor but it not working
```
  useEffect(() => {
    
    if (quill) {      
      quill.blur();
    }
  }, [quill]);
  ```

**Comment by gtgalone** [comment]
Hello! @fvn-manhtd 

In which case would you like to use it?

If you want to add blur listener, like below

https://codesandbox.io/s/react-quilljs-basic-forked-h62fho

**Comment by fvn-manhtd** [comment]
Thanks you for your reply

> Hello! @fvn-manhtd
> 
> In which case would you like to use it?
> 
> If you want to add blur listener, like below
> 
> https://codesandbox.io/s/react-quilljs-basic-forked-h62fho
