### ISSUE TITLE
compatibility issue with ViteJS and other esbuild based bundler

### ISSUE THREAD

**Issue by dohomi** [gtgalone/react-quilljs#56]
As discussed with previous PRs require is not compatible with ViteJS and other esbuild bundlers
https://github.com/gtgalone/react-quilljs/blob/master/index.ts#L86

It breaks the build and prevents from production bundling for example with ViteJS and Storybook

**Comment by gtgalone** [comment]
Hi! @dohomi 

Could ask to VitaJS?

It might be from VitaJS or configuration

because this package is working well in all environments for now.

**Comment by itsUndefined** [comment]
I could try to investigate this over the weekend since I have a webpack build that fails on 1.3.2 ( fix for vite )

**Comment by dohomi** [comment]
I think the solution is following config for ViteJS:
```ts
build: {
 commonjsOptions: {
  transformMixedEsModules: true,
 },
}
```
