### ISSUE TITLE
Adding plugin: counter module failed to work properly

### ISSUE THREAD

**Issue by SkyYap** [gtgalone/react-quilljs#61]
In the [readme](https://github.com/gtgalone/react-quilljs#counter) section, I have used the given instruction and found out the default counterRef is showing 2. It failed to work when I type first word but when I type second word, the counterRef turns to 3. 

Exp:

[ ] -> 2 words 
Hello -> 2 words
Hello world -> 3 words
Hello world, Quill -> 4 words

Is there any issue with the demo code?

**Comment by gtgalone** [comment]
Hello @SkyYap 

I just got this example from https://quilljs.com/guides/building-a-custom-module/#counting-words

maybe you can create this issue to https://github.com/quilljs/quill
