### ISSUE TITLE
Duplicate Toolbar Issue

### ISSUE THREAD

**Issue by RayNCooper** [gtgalone/react-quilljs#62]
First of all, thank you for the work you've done - it is much appreciated

The issue on hand is that the toolbar is always displayed twice on reload of a page.
I am using react-quills with React 18 and  Next.js 13. 
The issue I am having is the same as described here: https://github.com/zenoamaro/react-quill/issues/784

**Comment by gtgalone** [comment]
Hello @RayNCooper 

I have just tested. everything is working for me with that version.

![Screen Shot 2023-03-21 at 12 17 34 PM](https://user-images.githubusercontent.com/23162037/226717663-beac4db7-538a-4355-a8ee-2a85e88783b1.png)
