### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Sido-A** [gtgalone/react-quilljs#65]
Hi there,

I'm having issue with `Uncaught ReferenceError: require is not defined` as on attched image.
I saw past issues but is it not going to work if it's React V12^?

Thanks!

![image](https://github.com/gtgalone/react-quilljs/assets/44204865/855ccae3-521d-48e4-a6b8-a9e2394f90d9)

```
 "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@reduxjs/toolkit": "^1.9.0",
    "firebase": "^9.23.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-quilljs": "^1.3.3",
    "react-redux": "^8.0.5",
    "uuid": "^9.0.0"
  },
```

**Comment by gtgalone** [comment]
Hello @Sido-A !

You need to install quill too.

please install with npm or yarn add quill
