### ISSUE TITLE
Using quill.clipboard.dangerouslyPasteHTML() breaks the layout

### ISSUE THREAD

**Issue by vinodsptharsha** [gtgalone/react-quilljs#68]
I am using this plugin in an Expo React Native project for the web platform. It is working great with core features. When I used it with Material Top Tabs Navigator it broke the entire page's layout by taking a large width when HTML content was initialized with `quill.clipboard.dangerouslyPasteHTML()` Otherwise it works as expected. 

<img width="1120" alt="image" src="https://github.com/gtgalone/react-quilljs/assets/114156301/f99fb085-5266-4ac8-8561-05349fcd47c4">

**Comment by gtgalone** [comment]
Hello @vinodsptharsha 

I think you can try to use delta instead of raw html.

and this issue related to main quill package. I will close it :)

Thanks!
