### ISSUE TITLE
[Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.

### ISSUE THREAD

**Issue by Imki123** [gtgalone/react-quilljs#7]
Hi. There are some warnings in chrome devtool.

Can i remove this warning?

**Comment by gtgalone** [comment]
I don't think this problem is related to react-quilljs.

How about open issue with react https://github.com/facebook/react/issues

:)

**Comment by jraoult** [comment]
@gtgalone @imki123  I get a few of those as well. I think this is no an issue with React (who is just trying to help here) but the right way to address this would be for Quill to use `MutationObserver` (if possible), see https://github.com/quilljs/quill/issues/2030
