### ISSUE TITLE
Module integration not working

### ISSUE THREAD

**Issue by devdcodes9** [gtgalone/react-quilljs#70]
Tryig to use this plug in for emojis - https://github.com/contentco/quill-emoji .
Plugin is getting registered successfully but not able to add it to toolbar. Getting this error. Please help.
![image](https://github.com/gtgalone/react-quilljs/assets/155435515/75d336b5-60a3-412a-b901-2a19240ab512)

Registeration
`Quill.register('modules/emoji', Emoji, true);`

Toolbar
`const { quill, quillRef, Quill } = useQuill({
    modules: {
      table: false,
      'better-table': {
        operationMenu: {
          items: {
            unmergeCells: {
              text: 'Another unmerge cells name',
            },
          },
        },
      },
      keyboard: {
        bindings: QuillBetterTable.keyboardBindings,
      },
      mention: allowMention && {
        allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
        mentionDenotationChars: mentionChars,
        onSelect: onMentionSelect,
        renderItem: renderMentionItem,
        source: onSearchMention,
        showDenotationChar: showDenotationChar,
      },
      toolbar: disableToolbar
        ? false
        : toolbarOptions || {
            container: [
              ['bold', 'italic', 'underline', 'strike', 'blockquote'],
              [{ header: 1 }, { header: 2 }],
              [{ list: 'ordered' }, { list: 'bullet' }],
              [{ script: 'sub' }, { script: 'super' }],
              [{ indent: '-1' }, { indent: '+1' }],
              [{ color: [] }, { background: [] }],
              [{ font: [] }],
              [{ align: [] }],
              ['link', 'image', 'video'],
              ['clean'],
              ['emoji'],
              ['table'],
            ],
            },
          },
      'emoji-toolbar': true,
      // 'emoji-textarea': false,
      // 'emoji-shortname': true,
    },
  });`

**Comment by devdcodes9** [comment]
Not really, but I tried making a new package for quill-emoji for react-quilljs.
You can try using it : [quill-emojijs](https://www.npmjs.com/package/@devdcodes9/quill-emojijs)

**Comment by gtgalone** [comment]
I think this issue is not related with this package.
