### ISSUE TITLE
TypeError: obj.Quill is not a constructor

### ISSUE THREAD

**Issue by boyanhtrai** [gtgalone/react-quilljs#73]
I upgraded new version and I got this error below:

Version: "react-quilljs": "^1.3.4",
Error:
![image](https://github.com/gtgalone/react-quilljs/assets/29662022/9fa42d44-389c-4bd0-9872-e2a0150c5a5e)

You can use [Code Sandbox Playground Example](https://codesandbox.io/s/react-quilljsbasic-wm0uk) link in document and upgrade new version. You will get this error.

**Comment by alirezatbp** [comment]
Any fix to this?

**Comment by gtgalone** [comment]
Hi @boyanhtrai @alirezatbp 

I will fix it soon until then please use 1.3.3 without ^1.3.4

**Comment by gtgalone** [comment]
for me it is working well.

you need to update left side react-quilljs version 1.2.8 to 1.3.4

<img width="1196" alt="Screenshot 2024-05-25 174335" src="https://github.com/gtgalone/react-quilljs/assets/23162037/acd9502c-94ce-4c4d-bdd5-75204d7be5bd">

**Comment by boyanhtrai** [comment]
@gtgalone thanks for supporting. This one is working well but I have an issue why can I not use  "quill": "^2.0.2" and "react-quilljs": "^1.3.4" together? Because I still have a warning as below with "quill": "^1.3.7". This warning was fixed when upgrading "quill": "^2.0.2" .

<img width="685" alt="image" src="https://github.com/gtgalone/react-quilljs/assets/29662022/c2fbc37a-ca9e-4f23-a4d7-29c7949e88a4">
