### ISSUE TITLE
Uncaught TypeError: obj.Quill is not a constructor

### ISSUE THREAD

**Issue by vtrphan** [gtgalone/react-quilljs#74]
i got this error after updating to Quill 2.0.2, react-quilljs version is 1.3.4

**Comment by anehkumar** [comment]
I am also getting the same error, do you happen to find any fix?

**Comment by gtgalone** [comment]
Hi @vtrphan @anehkumar 

I just updated this package. 

Please use version 2.0.0. Thanks.
