### ISSUE TITLE
quill Cannot register "clean" specified in "formats" config. Are you sure it was registered?

### ISSUE THREAD

**Issue by boyanhtrai** [gtgalone/react-quilljs#75]
Show "quill Cannot register "clean" specified in "formats" config. Are you sure it was registered?" error in console log in [Code Sandbox Playground Example](https://codesandbox.io/s/react-quilljsbasic-wm0uk)

<img width="1510" alt="Screenshot 2024-06-05 at 15 21 14" src="https://github.com/gtgalone/react-quilljs/assets/29662022/07f4c454-1e1b-4a8e-b465-e453e6f1cd6c">

Version:
"react-quilljs": "^2.0.0",
"quill": "^2.0.2",

**Comment by tealtony** [comment]
I'm seeing the same thing on a clean install of both the same versions.

**Comment by gtgalone** [comment]
@OllieEdge Thanks for the nice solution!

**Comment by AlesSrsen** [comment]
@gtgalone Could this empty array for formats be set by default? I've just installed this dependency, used it the way it was shown on NPM and got this error. I believe it would be better if this was sorted out for the user by default.

**Comment by maznevskia** [comment]
I just addressed this issue in my Pull Request here: https://github.com/gtgalone/react-quilljs/pull/91

**Comment by gtgalone** [comment]
@AlesSrsen I have released new version with #91.
