### ISSUE TITLE
Not hide placeholder when entering the word in the text editor

### ISSUE THREAD

**Issue by boyanhtrai** [gtgalone/react-quilljs#76]
Not hide placeholder when entering the word in the text editor

<img width="1489" alt="image" src="https://github.com/gtgalone/react-quilljs/assets/29662022/fe03b58b-1e94-41b0-b1ca-e02d36e83f2c">

version: 
"react-quilljs": "^2.0.0",
"quill": "^2.0.2",

**Comment by gtgalone** [comment]
Hello @boyanhtrai !

For me, it is working good.

https://codesandbox.io/p/sandbox/react-quilljsbasic-wm0uk?file=%2Fsrc%2FApp.js%3A13%2C66

**Comment by boyanhtrai** [comment]
I can reproduce when you typing Japanese, Vietnamese or so on
