### ISSUE TITLE
Support for table

### ISSUE THREAD

**Issue by Ghoral24** [gtgalone/react-quilljs#78]
Hi,
I read in documentation that quill supports table in version 2.0. It does supports the insertion of table but It just inserts plain <p> tags.
![Screenshot from 2024-06-10 17-13-09](https://github.com/gtgalone/react-quilljs/assets/172269817/5dbf027f-9f6b-4822-be5e-e4a7719b254f)

I have tried all the other third party packages like quill-better table etc..but none of them seems to work. 
If you see this [demo](https://codepen.io/quill/pen/QxypzX), quill does supports the table. So maybe the issue is with the react-quilljs.

I have added a [demo](https://codesandbox.io/p/sandbox/react-quilljs-basic-forked-wxy74f?file=%2Fsrc%2FApp.js) as well.

Thannk you.

**Comment by gtgalone** [comment]
Hello @Ghoral24 

Maybe could you ask to plugin repo?
