### ISSUE TITLE
toolbar 'code-block', 'blockquote' is not working

### ISSUE THREAD

**Issue by Imki123** [gtgalone/react-quilljs#8]
I want to use them.
How can i use them?

**Comment by gtgalone** [comment]
You should follow with custom options https://github.com/gtgalone/react-quilljs#custom-all-options
:)

```
const modules = {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike', 'code-block', 'blockquote'],
    ],
  };

const placeholder = 'Compose an epic...';

const formats = ['bold', 'italic', 'underline', 'strike', 'code-block', 'blockquote'];

const { quillRef } = useQuill({ theme, modules, formats, placeholder });
```

**Comment by Imki123** [comment]
Wow. It's working after adding formats!
What does formats work?

**Comment by gtgalone** [comment]
Yes, That is important. You should let editor know how to use module with format. It required by quill.

**Comment by Ahmeed2m** [comment]
@gtgalone How do I create a handler for a custom format I added?
In the codesandbox below I added 'redo' and 'undo' to the toolbar with custom icons and added them to formats, then configured the handlers in the useEffect but with no luck, I tried the quilljs way of defining the handlers in the toolbar object but no luck either.
it doesn't call the handlers functions and logs the warning `quill:toolbar ignoring attaching to nonexistent format undo`

https://codesandbox.io/s/react-quilljsredo-undo-qqvtx

**Comment by gtgalone** [comment]
@Ahmeed2m 

Thank you for using and issuing.

https://codesandbox.io/s/react-quilljsredo-undo-forked-r1co3?file=/src/App.js

you need to add default undo redo function in toolbar, when it initialize.

```
handlers: {
  undo: () => {},
  redo: () => {}
}
```
