### ISSUE TITLE
Reference error: require is not defined (esm/index.js line 72)

### ISSUE THREAD

**Issue by jituiitm** [gtgalone/react-quilljs#80]
Hi, Thanks for this package.

In production, if we run this, then it throws the error that require is not defined.

I checked and found that, in _**esm/index.js file line 72**_, you should change require to import to fix this issue. 

Can you please update your package with this fix?

Thanks

**Comment by luanraithz** [comment]
For anyone having this problem just copy the lib source code and edit on your project.

**Comment by gtgalone** [comment]
@jituiitm @luanraithz Thanks! please update to 2.0.1

**Comment by lukenvn** [comment]
hi @gtgalone 
even 2.0.3 the problem still exist 
thanks @luanraithz  your solution worked
