### ISSUE TITLE
ESM should use dynamic import instead of require

### ISSUE THREAD

**Issue by steven-resonance** [gtgalone/react-quilljs#83]
The library is working great! But, when running tests with vitest, the imports are breaking for two reasons.

1. [vitest uses Node module resolution](https://github.com/vitest-dev/vitest/discussions/4233), which ignores `module`, so to tell an ESM based project to use `esm/index.js` during testing, you must include the `exports` property in package.json. An example of how that would look is below.
2. There is a `require('quill')` in `esm/index.js`, which still causes resolution to break in ESM environments. This would need to be changed to a dynamic import (`import('quill')`).

```json
  "exports": {
    "require": "./lib/index.js",
    "import": "./esm/index.js",
    "default": "./lib/index.js"
  },
```

**Comment by frontendpm** [comment]
have the same issue!

**Comment by gtgalone** [comment]
@steven-resonance @frontendpm Thanks Please update to 2.0.1
