### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by axelc-una** [gtgalone/react-quilljs#85]
So when I deployed the code to hosting, it was an error. 
![image](https://github.com/gtgalone/react-quilljs/assets/135933755/a05d9b99-e684-4bb7-a714-3416dcb87ab9)

but on my local environment, it works. Any information to fix it? 
![image](https://github.com/gtgalone/react-quilljs/assets/135933755/cdc82586-e760-4e49-8f43-81476be7c340)

I've tried the suggested installation.

This is my package. json
![image](https://github.com/gtgalone/react-quilljs/assets/135933755/ae099f3a-da6a-401e-a3d3-d0d01b58dde4)

and this is my code.

![image](https://github.com/gtgalone/react-quilljs/assets/135933755/61e09cde-df14-466d-807c-a3fa5a4ec549)
![image](https://github.com/gtgalone/react-quilljs/assets/135933755/804b3941-f324-49e1-bf94-e9bdbde689e8)

**Comment by gtgalone** [comment]
@axelc-una Thanks! Please update to 2.0.1

**Comment by rodr1vs** [comment]
Sorry to resurrect this but I'm getting  the same error since v2 (2.0.1, 2.0.2 or 2.0.3).
I'm using vite, not sure if that is related to this issue.

**Comment by Niraj-Dilshan** [comment]
im facing the same issue i have also tried 2.0.1, 2.0.2 and 2.0.3

**Comment by rodr1vs** [comment]
I added this option in vite to fix temporally the issue:
```js
   build: {
          commonjsOptions: {
            transformMixedEsModules: true,
          },
        }
```
