### ISSUE TITLE
Quill.register is not a function (v2.0.1)

### ISSUE THREAD

**Issue by rodr1vs** [gtgalone/react-quilljs#86]
I just updated to 2.0.1 and I'm getting an error when trying to register plugins with Quill.

```
  if (Quill && !quill) {
    Quill.register({
```

In the past that was working but now is throwing an error:
```
Uncaught TypeError: Quill.register is not a function
```

It seems that now Quill is returning a promise.

Not sure if is related that I'm using vite.

**Comment by gtgalone** [comment]
Hello @rodr1vs !

Please use 2.0.2 Thanks!

**Comment by rodr1vs** [comment]
Thank you!
