### ISSUE TITLE
encounter the error Module parse failed

### ISSUE THREAD

**Issue by luc345** [gtgalone/react-quilljs#87]
Environment: Next.js 14.2.5, React Quilljs 2.0.2.

 I have already set experimental: { esmExternals: "loose" }, but I still encounter the error Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0). 

Please assist. Appreciate your help

**Comment by maxrpark** [comment]
Same issue here. I used React Quilljs two months ago on another project, same setup but now I encounter this error.

**Comment by gtgalone** [comment]
@luc345 @maxrpark  Could you guys update 2.0.3?

Thanks!

**Comment by luc345** [comment]
OK Thanks @gtgalone
