### ISSUE TITLE
Image style size not working when set default value. 

### ISSUE THREAD

**Issue by imrostom** [gtgalone/react-quilljs#89]
this is my code `
      quill.clipboard.dangerouslyPasteHTML('<img style="width: 100px" src="myimagecdn"/>');`

**Comment by imrostom** [comment]
Issue fixed, after adding this code `// BEGIN allow image alignment styles
const ImageFormatAttributesList = ['alt', 'height', 'width', 'style'];
const BaseImageFormat = Quill.import('formats/image');

class ImageFormat extends BaseImageFormat {
  static formats(domNode) {
    return ImageFormatAttributesList.reduce(function (formats, attribute) {
      if (domNode.hasAttribute(attribute)) {
        formats[attribute] = domNode.getAttribute(attribute);
      }
      return formats;
    }, {});
  }
  format(name, value) {
    if (ImageFormatAttributesList.indexOf(name) > -1) {
      if (value) {
        this.domNode.setAttribute(name, value);
      } else {
        this.domNode.removeAttribute(name);
      }
    } else {
      super.format(name, value);
    }
  }
}

Quill.register(ImageFormat, true);
// END allow image alignment styles
`

**Comment by gtgalone** [comment]
Thanks @imrostom
