### ISSUE TITLE
404 Error: quill package not found in npm registry

### ISSUE THREAD

**Issue by noman-maken** [gtgalone/react-quilljs#99]
**Bug:**
I'm trying to install `react-quilljs@^1.3.3`, but when running `npm install`, I get the following error:

npm warn   react-quilljs@"^1.3.3" from the root project
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/quill - Not found
npm error 404
npm error 404  'quill@^1.3.7 || ^2.0.2' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git URL.

![image](https://github.com/user-attachments/assets/60c5f009-da9f-417d-bb23-3d3c98a9054e)

**Steps to reproduce:**
1. Run `npm install react-quilljs@^1.3.3` in a Next.js project.
2. Observe the 404 error when trying to resolve `quill@^1.3.7`.

**Expected behavior:**
The package `quill` should be found and installed correctly from the npm registry.

**Environment:**
- Node version: v22.8.0
- npm version: 10.9.0
- `react-quilljs` version: ^1.3.3

- I have already tried clearing the npm cache and checking the registry URL, but the issue persists.

**Comment by gtgalone** [comment]
Hi @noman-maken 

You need to install quill.

Thanks
